/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Kenji
 */
public class ArtistFrame extends javax.swing.JFrame {

    public enum Modes {
        NEW,
        UPDATE
    }
    public Modes mode = Modes.NEW;
    public Connection connection;

    /**
     * Creates new form MainForm
     */
    public ArtistFrame() {
        initComponents();
        refresh();
        mode = Modes.NEW;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        artist_id_label = new javax.swing.JLabel();
        artist_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        artistList = new javax.swing.JList<>();
        newButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        artist_name_label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        artist_name = new javax.swing.JTextField();
        record_label_id = new javax.swing.JTextField();
        record_label_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gabriel's Contact Form");

        artist_id_label.setText("ID");

        artist_id.setToolTipText("");
        artist_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist_idActionPerformed(evt);
            }
        });

        artistList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        artistList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                artistListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(artistList);

        newButton.setText("New");
        newButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Artists");

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        artist_name_label.setText("Name");

        artist_name.setToolTipText("");
        artist_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artist_nameActionPerformed(evt);
            }
        });

        record_label_id.setToolTipText("");
        record_label_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_label_idActionPerformed(evt);
            }
        });

        record_label_label.setText("Record Label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(284, 284, 284))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton)
                                .addGap(18, 18, 18)
                                .addComponent(saveButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(artist_name_label)
                                        .addGap(18, 18, 18)
                                        .addComponent(artist_name, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(artist_id_label)
                                                .addGap(18, 18, 18)
                                                .addComponent(artist_id, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(record_label_label)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(record_label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))))))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(artist_id_label)
                            .addComponent(artist_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(artist_name_label)
                            .addComponent(artist_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(record_label_label)
                            .addComponent(record_label_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newButton)
                    .addComponent(deleteButton)
                    .addComponent(saveButton))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void artist_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artist_idActionPerformed

    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        artist_id.setText("");
        record_label_id.setText("");
        artist_name.setText("");
        mode = Modes.NEW;
        System.out.println("Mode: " + mode.toString());
    }//GEN-LAST:event_newButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void artistListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_artistListValueChanged
        int index = artistList.getSelectedIndex();
        System.out.println("Index Selected: " + index);
        String s = (String) artistList.getSelectedValue();
        System.out.println("Value Selected: " + s);
        String[] parts = s.split("-");
        String ID = parts[0].trim();
        System.out.println("ID: " + ID);
        updateform(ID);
        mode = Modes.UPDATE;
        System.out.println("Mode: " + mode.toString());

    }//GEN-LAST:event_artistListValueChanged
    private boolean connect() {
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/Team3Project", "root", "");
            return true;
        } catch (Exception e) {
            System.out.println("Error - database could not connect\n" + e.getMessage());
            return false;
        }

    }
    private void artist_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artist_nameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_artist_nameActionPerformed
    private boolean checkLabel(int id) {
        try {
            if (connect()) {
                String query = "select * from record_label where record_label_id =" + id;
                Statement sta = connection.createStatement();
                ResultSet rs = sta.executeQuery(query);
                if (!rs.next()) {
                    //no rows exist so return false;
                    connection.close();
                    return false;
                } else {
                    connection.close();
                    return true;
                }

            }
        } catch (Exception e) {
            System.out.println("Error connecting to the database\n" + e.getMessage());
            return true;
        }
        return true;
    }
    
    private boolean checkId(int id) {
        try {
            if (connect()) {
                String query = "select * from artist where artist_id =" + id;
                Statement sta = connection.createStatement();
                ResultSet rs = sta.executeQuery(query);
                if (!rs.next()) {
                    //no rows exist so return false;
                    connection.close();
                    return false;
                } else {
                    connection.close();
                    return true;
                }

            }
        } catch (Exception e) {
            System.out.println("Error connecting to the database\n" + e.getMessage());
            return true;
        }
        return true;
    }
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int id = 0;
        int labelId = 0;
        
        try {
            id = Integer.parseInt(artist_id.getText());
            labelId =  Integer.parseInt(record_label_id.getText());
            
            if ((checkId(id))) {
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(new JFrame(), "Error - ID is not a number");
        }
        String _id = artist_id.getText();
        String _name = artist_name.getText();
        String _recordlabel = record_label_id.getText();
        System.out.println("Id: " + id);

        if (mode == Modes.NEW) {
            System.out.println("Save " + mode.toString() + " mode");
            if (checkId(id)) {
                JOptionPane.showMessageDialog(new JFrame(), "Error - ID or Record Label already exists. Choose new values.");
            } else {
                try {
                    if (connect()) {
                        String query = "Insert into artist (artist_id, artist_name, record_label_id)"
                                + "values(?, ?, ?)";
                        PreparedStatement stmnt = connection.prepareStatement(query);
                        stmnt.setInt(1, id);
                        stmnt.setString(2, _name);
                        stmnt.setInt(3, labelId);


                        int row = stmnt.executeUpdate();
                        System.out.println("Rows affected:" + row); //1
                        JOptionPane.showMessageDialog(new JFrame(), "Added User: " + id + " - " + _name + " " + _recordlabel + " to the Database");
                        connection.close();
                    }
                } catch (Exception e) {
                    System.out.println(e);
                    JOptionPane.showMessageDialog(new JFrame(), "Error - could not connect to the database");
                }

            }

        } else if (mode == Modes.UPDATE) {
            System.out.println("Save " + mode.toString() + " mode");
            
            try {
                if (connect()) {
                    String query = "Update artist set artist_name=? where artist_id=?";
                    PreparedStatement stmnt = connection.prepareStatement(query);

                    stmnt.setInt(2, id);
                    stmnt.setString(1, _name);
                             
                    int row = stmnt.executeUpdate();
                    System.out.println("Rows affected:" + row); //1
                    JOptionPane.showMessageDialog(new JFrame(), "Updated User: " + _id + " - " + _name + " " + _recordlabel + " to the Database");
                    connection.close();
                } else {
                }

            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(new JFrame(), "Error - could not connect to the database");
            }

        } else {
            System.out.println("No mode selected");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (mode == Modes.UPDATE) {
            int id = 0;
            id = Integer.parseInt(artist_id.getText());

            try {
                if (connect()) {
                    String query = "Delete from artist where artist_id=?";
                    PreparedStatement stmnt = connection.prepareStatement(query);
                    stmnt.setInt(1, id);
                    int row = stmnt.executeUpdate();
                    System.out.println("Rows affected:" + row); //1
                    JOptionPane.showMessageDialog(new JFrame(), "Deleted User: " + id + " from the Database");
                    connection.close();
                } else {
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(new JFrame(), "Error - could not connect to the database");
            }
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Error - Update mode not selected");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void record_label_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_label_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_record_label_idActionPerformed
    public void refresh() {
        try {
            if (connect()) {

                String query = "select * from artist";

                Statement sta = connection.createStatement();
                ResultSet rs = sta.executeQuery(query);
                DefaultListModel listModel;
                listModel = new DefaultListModel();
                while (rs.next()) {
                    listModel.addElement(rs.getString("artist_id") + " - " + rs.getString("artist_name") + ", " + rs.getString("record_label_id"));
                }
                artistList.setModel(listModel);

                connection.close();
            }
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    public void updateform(String id) {
        try {
            if (connect()) {

                String query = "select * from artist where artist_id=" + id;

                Statement sta = connection.createStatement();
                ResultSet rs = sta.executeQuery(query);
                while (rs.next()) {
                    artist_id.setText(rs.getString("artist_id"));
                    artist_name.setText(rs.getString("artist_name"));
                    record_label_id.setText(rs.getString("record_label_id"));
                    
                }

                connection.close();
            }
        } catch (Exception exception) {
            exception.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArtistFrame().setVisible(false);
                new MainForm().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> artistList;
    private javax.swing.JTextField artist_id;
    private javax.swing.JLabel artist_id_label;
    private javax.swing.JTextField artist_name;
    private javax.swing.JLabel artist_name_label;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newButton;
    private javax.swing.JTextField record_label_id;
    private javax.swing.JLabel record_label_label;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
